"""Tests for the per-service rtl-airband config builder.

Background
----------
The MA/SL split-process architecture (docs/rspduo_ma_sl_split.md) ends
the "one combined config, two device blocks, one rtl-airband process"
approach.  Each band gets its own rtl-airband instance with its own
config, generated by ``build_service_config()``.

This module pins the contract that build_service_config emits:

- A complete, parseable-by-rtl-airband config in libconfig syntax
- Exactly ONE device block (no leakage of the other band's tuner)
- A stats_filepath that's per-service (so the watchdog can distinguish)
- An icecast block on a per-service mount (so the dashboard can route)
- Channel outputs rewritten to the per-service mixer name
- Idempotent: re-rendering the same inputs gives the same output

The function is exercised end-to-end against synthetic profile text
that mirrors what production profiles look like post-migration.
"""
from __future__ import annotations

import os
import tempfile
import textwrap
import unittest

from combined_config import (
    build_service_config,
    extract_devices_payload,
)


# Mirror the multi-line layout production profiles use post-migration.
# The single-line ``channels: ( { ... outputs: ( ... ); } );`` form
# collides with replace_outputs_with_mixer's line-based scanner —
# rtl-airband-emitted configs always put each brace/paren on its own
# line, so the function was only designed against that shape.
AIRBAND_PROFILE = textwrap.dedent('''\
    airband = true;
    log_scan_activity = true;
    stats_filepath = "/run/rtl_airband_stats.txt";

    devices:
    ({
      type = "soapysdr";
      device_string = "driver=sdrplay,serial=1809063632,mode=MA,tuner=1";
      sample_rate = 1000000;
      mode = "scan";
      gain = 32.800;

      channels:
      (
        {
          freqs = (121.500, 124.600, 127.700);
          modulation = "am";
          bandwidth = 12000;
          squelch_threshold = -27;

          outputs:
          (
            {
              type = "mixer";
              name = "combined";
            }
          );
        }
      );
    });

    mixers: {
      combined: {
        outputs:
        (
          {
            type = "icecast";
            server = "127.0.0.1";
            port = 8000;
            mountpoint = "ANALOG.mp3";
            username = "source";
            password = "062352";
            name = "SprontPi Radio";
            bitrate = 24;
          }
        );
      };
    };
''')


GROUND_PROFILE = textwrap.dedent('''\
    airband = false;
    log_scan_activity = true;
    stats_filepath = "/run/rtl_airband_stats.txt";

    devices:
    ({
      type = "soapysdr";
      device_string = "driver=sdrplay,serial=1809063632,mode=SL,tuner=2";
      sample_rate = 1000000;
      mode = "scan";
      gain = 29.700;

      channels:
      (
        {
          freqs = (151.0775, 154.130, 155.565);
          modulation = "nfm";
          bandwidth = 12500;
          squelch_threshold = -27;

          outputs:
          (
            {
              type = "mixer";
              name = "combined";
            }
          );
        }
      );
    });

    mixers: {
      combined: {
        outputs:
        (
          {
            type = "icecast";
            server = "127.0.0.1";
            port = 8000;
            mountpoint = "ANALOG.mp3";
            username = "source";
            password = "062352";
            bitrate = 24;
          }
        );
      };
    };
''')


UI_DISABLED_PROFILE = textwrap.dedent('''\
    airband = true;
    ui_disabled = true;
''')


def _write_profile(text: str) -> str:
    fh = tempfile.NamedTemporaryFile(
        mode="w", suffix="_test_profile.conf", delete=False
    )
    fh.write(text)
    fh.close()
    return fh.name


class AirbandRenderingTests(unittest.TestCase):
    def setUp(self) -> None:
        self.path = _write_profile(AIRBAND_PROFILE)
        self.addCleanup(lambda: os.unlink(self.path))

    def _render(self, **overrides) -> str:
        kwargs = dict(
            profile_path=self.path,
            service="airband",
            mixer_name="combined_airband",
            mount_name="ANALOG.mp3",
            stats_filepath="/run/rtl_airband_airband_stats.txt",
        )
        kwargs.update(overrides)
        return build_service_config(**kwargs)

    def test_emits_airband_flag_true(self) -> None:
        text = self._render()
        self.assertIn("airband = true;", text)
        self.assertNotIn("airband = false;", text)

    def test_emits_per_service_stats_filepath(self) -> None:
        text = self._render()
        self.assertIn('stats_filepath = "/run/rtl_airband_airband_stats.txt"', text)
        # The default stats path from the profile must NOT survive — we
        # explicitly pass a service-specific path.
        self.assertNotIn('stats_filepath = "/run/rtl_airband_stats.txt"', text)

    def test_only_one_device_block(self) -> None:
        text = self._render()
        device_payload = extract_devices_payload(text)
        # Exactly one opening brace at the device-block level.  A
        # leakage of a second device block would show multiple
        # top-level ``{ ... }`` units inside ``devices: ( ... );``.
        self.assertEqual(
            device_payload.count('type = "soapysdr"'),
            1,
            f"expected exactly one soapysdr device block, got:\n{device_payload}",
        )

    def test_preserves_ma_mode_device_string(self) -> None:
        text = self._render()
        self.assertIn(
            'device_string = "driver=sdrplay,serial=1809063632,mode=MA,tuner=1"',
            text,
            "MA-mode device_string must pass through verbatim",
        )

    def test_channel_output_rewired_to_service_mixer(self) -> None:
        text = self._render()
        # The channels in the input declared name="combined"; the
        # output should now reference our service-specific mixer name.
        self.assertIn('name = "combined_airband"', text)
        # And the bare "combined" mixer name from the input must NOT
        # leak through — a stale reference would route to a non-existent
        # mixer and the channel would be silent.
        # Be careful: "combined_airband" contains "combined", so the
        # substring test has to be precise — quote-bounded.
        self.assertNotIn('name = "combined";', text)

    def test_icecast_mount_overridden_to_argument(self) -> None:
        text = self._render(mount_name="ANALOG.mp3")
        self.assertIn('mountpoint = "ANALOG.mp3"', text)

    def test_icecast_mount_can_be_renamed(self) -> None:
        text = self._render(mount_name="AIRBAND_TEST.mp3")
        self.assertIn('mountpoint = "AIRBAND_TEST.mp3"', text)

    def test_icecast_continuous_flag_present(self) -> None:
        text = self._render(analog_continuous=True)
        self.assertIn("continuous = true", text)

    def test_idempotent_rendering(self) -> None:
        a = self._render()
        b = self._render()
        self.assertEqual(a, b, "two calls with same args must produce identical output")


class GroundRenderingTests(unittest.TestCase):
    def setUp(self) -> None:
        self.path = _write_profile(GROUND_PROFILE)
        self.addCleanup(lambda: os.unlink(self.path))

    def _render(self, **overrides) -> str:
        kwargs = dict(
            profile_path=self.path,
            service="ground",
            mixer_name="combined_ground",
            mount_name="ANALOG_GROUND.mp3",
            stats_filepath="/run/rtl_airband_ground_stats.txt",
        )
        kwargs.update(overrides)
        return build_service_config(**kwargs)

    def test_emits_airband_flag_false(self) -> None:
        text = self._render()
        self.assertIn("airband = false;", text)
        self.assertNotIn("airband = true;", text)

    def test_sl_mode_device_string_preserved(self) -> None:
        text = self._render()
        self.assertIn(
            'device_string = "driver=sdrplay,serial=1809063632,mode=SL,tuner=2"',
            text,
        )

    def test_ground_icecast_mount_is_analog_ground(self) -> None:
        text = self._render()
        self.assertIn('mountpoint = "ANALOG_GROUND.mp3"', text)
        # Must not still publish to plain ANALOG.mp3 — that's the
        # airband mount.  Two simultaneous sources to the same icecast
        # mount would conflict.
        # Word-boundary aware check:
        self.assertNotIn('mountpoint = "ANALOG.mp3"', text)

    def test_ground_uses_its_own_mixer_name(self) -> None:
        text = self._render()
        self.assertIn('name = "combined_ground"', text)
        self.assertNotIn('name = "combined_airband"', text)


class GuardrailTests(unittest.TestCase):
    def test_bad_service_name_rejected(self) -> None:
        path = _write_profile(AIRBAND_PROFILE)
        try:
            with self.assertRaises(ValueError) as ctx:
                build_service_config(
                    profile_path=path,
                    service="digital",  # not airband|ground
                    mixer_name="x",
                    mount_name="X.mp3",
                    stats_filepath="/run/x.txt",
                )
            self.assertIn("airband", str(ctx.exception))
            self.assertIn("ground", str(ctx.exception))
        finally:
            os.unlink(path)

    def test_ui_disabled_empty_profile_raises_for_caller_to_handle_fallback(self) -> None:
        # Profiles like none_airband.conf and none_ground.conf are
        # ``airband = ...; ui_disabled = true;`` with NO device block.
        # The build-service-config.py script is supposed to resolve
        # these to a fallback before invoking the renderer; if it
        # forgets and hands us the empty profile directly, we raise
        # loudly rather than emit a config that would crash
        # rtl-airband at startup.
        path = _write_profile(UI_DISABLED_PROFILE)
        try:
            with self.assertRaises(RuntimeError) as ctx:
                build_service_config(
                    profile_path=path,
                    service="airband",
                    mixer_name="combined_airband",
                    mount_name="ANALOG.mp3",
                    stats_filepath="/run/rtl_airband_airband_stats.txt",
                )
            self.assertIn("no usable device", str(ctx.exception))
        finally:
            os.unlink(path)

    def test_empty_profile_raises(self) -> None:
        # A profile with no device block (and not ui_disabled) is a
        # broken profile — refuse to silently produce a no-op config.
        path = _write_profile("airband = true;\n")
        try:
            with self.assertRaises(RuntimeError) as ctx:
                build_service_config(
                    profile_path=path,
                    service="airband",
                    mixer_name="combined_airband",
                    mount_name="ANALOG.mp3",
                    stats_filepath="/run/rtl_airband_airband_stats.txt",
                )
            self.assertIn("no usable device", str(ctx.exception))
        finally:
            os.unlink(path)


if __name__ == "__main__":
    unittest.main()
