airband = false;

devices:
({
  type = "rtlsdr";
  index = 1;
  mode = "scan";
  gain = 25.400;   # UI_CONTROLLED



  channels:
  (
    {
      freqs = (
        26.9650,
        26.9750,
        26.9850,
        27.0050,
        27.0150,
        27.0250,
        27.0350,
        27.0550,
        27.0650,
        27.0750,
        27.0850,
        27.1050,
        27.1150,
        27.1250,
        27.1350,
        27.1550,
        27.1650,
        27.1750,
        27.1850,
        27.2050,
        27.2150,
        27.2250,
        27.2550,
        27.2350,
        27.2450,
        27.2650,
        27.2750,
        27.2850,
        27.2950,
        27.3050,
        27.3150,
        27.3250,
        27.3350,
        27.3450,
        27.3550,
        27.3650,
        27.3750,
        27.3850,
        27.3950,
        27.4050
      );

      modulation = "am";
      bandwidth = 10000;
      squelch_threshold = -22;  # UI_CONTROLLED


      squelch_delay = 0.8;

      outputs:
      (
        {
          type = "icecast";
          send_scan_freq_tags = true;
          server = "127.0.0.1";
          port = 8000;
          mountpoint = "scannerbox.mp3";
          username = "source";
          password = "062352";
          name = "SprontPi Radio";
          genre = "AIRBAND";
          description = "Custom";
          bitrate = 32;
        }
      );
    }
  );
});
