airband = true;
log_scan_activity = true;
stats_filepath = "/run/rtl_airband_stats.txt";

devices:
({
  type = "rtlsdr";
  serial = "45469635";
  index = 0;
  mode = "scan";
  gain = 25.400;   # UI_CONTROLLED
































































































































































































































































































































































  channels:
  (
    {
      freqs = (
        118.4000,
        118.6000,
        119.3500,
        119.4500,
        122.7000,
        122.9500,
        124.5500,
        124.7500,
        127.1750
      );
      labels = (
        "Approach/Departure - East",
        "Tower",
        "Approach/Departure - West",
        "Tower",
        "Unicom / CTAF",
        "Unicom",
        "Clearance Delivery",
        "Final Approach",
        "Approach Control"
      );


      modulation = "am";
      bandwidth = 12000;

      // squelch_snr_threshold = 0.500;  # UI_CONTROLLED
      squelch_threshold = -45;  # UI_CONTROLLED






























































































































































































































































































































































      squelch_delay = 0.8;

      outputs:
      (
        {
          
          type = "icecast";
          send_scan_freq_tags = true;
          server = "127.0.0.1";
          port = 8000;
          mountpoint = "GND.mp3";
username = "source";
          password = "062352";
          name = "SprontPi Radio";
          genre = "AIRBAND";
          description = "Nashville Airband locals";
          bitrate = 32;
        }
      );
    }
  );
});
