airband = false;

devices:
({
  type = "rtlsdr";
  serial = "70613472";
  index = 1;
  mode = "scan";
  gain = 25.400;   # UI_CONTROLLED

  channels:
  (
    {
      freqs = (
        162.4000, 162.4250, 162.4500, 162.4750, 162.5000, 162.5250, 162.5500
      );

      labels = (
        "162.400 WX", "162.425 WX", "162.450 WX", "162.475 WX",
        "162.500 WX", "162.525 WX", "162.550 WX"
      );


      modulation = "nfm";
      bandwidth = 5000;

      squelch_snr_threshold = 3.500;  # UI_CONTROLLED
      squelch_delay = 0.8;

      outputs:
      (
        {
          
          type = "icecast";
          send_scan_freq_tags = true;
          server = "127.0.0.1";
          port = 8000;
          mountpoint = "GND.mp3";
username = "source";
          password = "062352";
          name = "SprontPi Radio";
          genre = "WX";
          description = "NOAA Weather Radio Scan";
          bitrate = 32;
}
      );
    }
  );
});
