airband = false;
log_scan_activity = true;

devices:
({
  type = "rtlsdr";
  serial = "70613472";
  index = 1;
  mode = "scan";
  gain = 20.700;   # UI_CONTROLLED

































































































































































  channels:
  (
    {
      freqs = (
        145.4700,
        146.5500,
        146.6700,
        442.8000,
        443.4750,
        443.7250,
        443.9750
      );
      labels = (
        "County ARES Secondary",
        "County ARES Tactical Simplex",
        "County ARES Primary",
        "MTEARS Nashville (Davidson Co) (19)",
        "MTEARS Franklin (Williamson County) (94B)",
        "MTEARS Hub - Nolensville (Williamson Co) (1)",
        "MTEARS Pasquo/Nashville (Davidson Co) (79)"
      );

      modulation = "nfm";
      bandwidth = 12000;

      // squelch_snr_threshold = 10.000;  # UI_CONTROLLED
      squelch_threshold = -35;  # UI_CONTROLLED































































































































































      squelch_delay = 0.8;

      outputs:
      (
        {
          type = "icecast";
          send_scan_freq_tags = true;
          server = "127.0.0.1";
          port = 8000;
          mountpoint = "FTC_GND.mp3";
          username = "source";
          password = "062352";
          name = "SprontPi Radio";
          genre = "MILITARY";
          description = "Ft. Campbell Ground";
          bitrate = 32;
        }
      );
    }
  );
});
