#!/usr/bin/env python3
"""Pre-flight bootstrap for the OP25 digital backend.

Generates runtime config for multi_rx.py — a single process managing all
dongles and systems simultaneously. Each system gets a dedicated SDR for
control + voice following. An optional third dongle acts as a roaming
traffic follower for the busiest system.

Output layout:

  /run/scannerproject/op25/tgid_tags.tsv     — shared talkgroup labels
  /run/scannerproject/op25/whitelist.tsv      — favorited TGID whitelist
  /run/scannerproject/op25/trunk.tsv          — OP25 trunking config
  /run/scannerproject/op25/multi_rx.json      — multi_rx.py JSON config
  /run/scannerproject/op25/start.sh           — launch script for multi_rx.py
  /run/scannerproject/op25/instances.json     — manifest (audio bridge + adapter)

Systemd unit scanner-digital-op25.service runs start.sh as a single process.
"""
from __future__ import annotations

import json
import os
import re
import stat
import subprocess
import sys

# Add project root to path so we can import ui modules.
_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _PROJECT_ROOT)

from ui.config import (
    DIGITAL_ACTIVE_PROFILE_LINK,
    OP25_DEFAULT_OFFSET,
    OP25_DEFAULT_SAMPLE_RATE,
    OP25_MULTI_RX_PATH,
    OP25_RUNTIME_DIR,
    OP25_STATUS_PORT,
)
from ui.dongle_allocator import load_assignments
from ui.op25_adapter import (
    _multi_rx_udp_ports,
    _flatten_active_runtime_systems,
    _hydrate_runtime_systems_for_config,
    _read_op25_system_config,
    _read_system_definitions,
    _read_talkgroup_labels,
    generate_multi_rx_config,
    generate_tgid_tags_tsv,
    generate_trunk_tsv,
)

# Base UDP port for audio output.
_UDP_AUDIO_BASE_PORT = 23456

_RTL_TEST_DEVICE_RE = re.compile(r"^\s*(\d+):\s+.*SN:\s+(\S+)\s*$")


def _safe_realpath(path: str) -> str:
    try:
        return os.path.realpath(path)
    except Exception:
        return path


def _resolve_active_profile() -> str:
    link = DIGITAL_ACTIVE_PROFILE_LINK
    if not link or not os.path.islink(link):
        return ""
    target = _safe_realpath(link)
    if target and os.path.isdir(target):
        return target
    return ""


def _build_dongle_map(dongle_assignments: dict | None) -> dict[str, str]:
    """Map system_name -> dongle serial from allocator assignments."""
    if not dongle_assignments:
        return {}
    serial_map: dict[str, str] = {}
    for entry in dongle_assignments.get("assignments") or []:
        sname = str(entry.get("system_name") or "").strip()
        serial = str(entry.get("preferred_tuner_serial") or "").strip()
        if sname and serial:
            serial_map[sname] = serial
    return serial_map


def _generate_multi_rx_start_script(config_path: str) -> str:
    """Generate shell script that launches multi_rx.py with the JSON config."""
    apps_dir = os.path.dirname(OP25_MULTI_RX_PATH)
    tdma_dir = os.path.join(apps_dir, "tdma")
    lines = [
        "#!/bin/bash",
        "# Auto-generated by ensure-op25-runtime.py — multi_rx.py mode",
        f'export PYTHONPATH="{apps_dir}:{tdma_dir}:${{PYTHONPATH:-}}"',
        f'cd "{apps_dir}"',
        f'exec python3 "{OP25_MULTI_RX_PATH}" \\',
        f'  -c "{config_path}" \\',
        f'  2>&1',
    ]
    return "\n".join(lines) + "\n"


def _detect_traffic_dongle(dongle_assignments: dict | None) -> str:
    """Find a traffic-pool dongle for use as traffic follower."""
    if not dongle_assignments:
        return ""
    pool = dongle_assignments.get("traffic_pool") or []
    if pool:
        return str(pool[0]).strip()
    return ""


def _parse_rtl_test_device_map(output: str) -> dict[str, int]:
    """Parse ``rtl_test`` output into ``{serial: index}``."""
    mapping: dict[str, int] = {}
    for line in str(output or "").splitlines():
        match = _RTL_TEST_DEVICE_RE.match(line.strip())
        if not match:
            continue
        index = int(match.group(1))
        serial = str(match.group(2) or "").strip()
        if serial:
            mapping[serial] = index
    return mapping


def _enumerate_rtlsdr_serial_index_map() -> dict[str, int]:
    """Enumerate current RTL-SDR serials to librtlsdr indices.

    Uses ``rtl_test -d 9999 -t`` so librtlsdr prints the device list but does
    not open any matching tuner.
    """
    cmd = ["rtl_test", "-d", "9999", "-t"]
    try:
        result = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            check=False,
            timeout=3,
        )
    except Exception:
        return {}
    return _parse_rtl_test_device_map(result.stdout or "")


def _build_dongle_arg_map(serials: list[str]) -> dict[str, str]:
    """Resolve OP25 dongle args for the requested serials.

    Prefer ``rtl=<index>`` when the current librtlsdr enumeration can map the
    serial to an index. Fall back to ``rtl=<serial>`` when no mapping is
    available so runtime generation remains resilient on hosts without
    ``rtl_test``.
    """
    mapping = _enumerate_rtlsdr_serial_index_map()
    args_map: dict[str, str] = {}
    seen: set[str] = set()
    for raw_serial in serials:
        serial = str(raw_serial or "").strip()
        if not serial or serial in seen:
            continue
        seen.add(serial)
        if serial in mapping:
            args_map[serial] = f"rtl={mapping[serial]}"
        else:
            args_map[serial] = f"rtl={serial}"
    return args_map


def main() -> int:
    profile_dir = _resolve_active_profile()
    if not profile_dir:
        print("ERROR: no active digital profile", file=sys.stderr)
        return 1

    profile_id = os.path.basename(profile_dir)
    print(f"OP25 runtime: profile={profile_id} dir={profile_dir}")

    op25_overrides = _read_op25_system_config(profile_dir)
    runtime_systems, _selector_state = _hydrate_runtime_systems_for_config(
        profile_dir,
        OP25_RUNTIME_DIR,
        op25_overrides=op25_overrides,
    )
    systems = _flatten_active_runtime_systems(runtime_systems)
    if not systems:
        print("ERROR: no systems defined in profile", file=sys.stderr)
        return 1
    print(f"OP25 runtime: {len(systems)} system(s) found")

    # Read dongle assignments.
    dongle_assignments = None
    try:
        dongle_assignments = load_assignments()
    except Exception as e:
        print(f"WARNING: could not load dongle assignments: {e}", file=sys.stderr)

    dongle_map = _build_dongle_map(dongle_assignments)
    tg_labels = _read_talkgroup_labels(profile_dir)

    runtime_dir = OP25_RUNTIME_DIR
    os.makedirs(runtime_dir, exist_ok=True)

    # Symlink OP25 www assets so the built-in HTTP server can serve
    # static files from ../www/www-static relative to the runtime dir.
    _op25_apps_dir = os.path.dirname(OP25_MULTI_RX_PATH)
    _op25_www_dir = os.path.join(os.path.dirname(_op25_apps_dir), "www")
    _runtime_www_dir = os.path.join(os.path.dirname(runtime_dir), "www")
    if os.path.isdir(_op25_www_dir) and not os.path.exists(_runtime_www_dir):
        try:
            os.symlink(_op25_www_dir, _runtime_www_dir)
            print(f"OP25 runtime: symlinked {_runtime_www_dir} -> {_op25_www_dir}")
        except OSError as exc:
            print(f"WARNING: could not create www symlink: {exc}", file=sys.stderr)

    # Shared talkgroup tags file.
    tags_content = generate_tgid_tags_tsv(tg_labels)
    tags_path = os.path.join(runtime_dir, "tgid_tags.tsv")
    _atomic_write(tags_path, tags_content)
    print(f"OP25 runtime: wrote {tags_path} ({len(tg_labels)} talkgroups)")

    # Generate whitelist from talkgroup labels so OP25 only follows
    # the user's favorited talkgroups — matches HP scanner behavior.
    whitelist_path = ""
    if tg_labels:
        whitelist_path = os.path.join(runtime_dir, "whitelist.tsv")
        wl_lines = [
            str(tgid)
            for tgid in sorted(tg_labels.keys(), key=lambda t: int(t) if t.isdigit() else 0)
        ]
        _atomic_write(whitelist_path, "\n".join(wl_lines) + "\n")
        print(f"OP25 runtime: wrote {whitelist_path} ({len(wl_lines)} talkgroups)")
        # Inject whitelist into overrides for all systems (unless already set).
        for sys_def in systems:
            sname = sys_def["name"]
            if sname not in op25_overrides:
                op25_overrides[sname] = {}
            if not op25_overrides[sname].get("whitelist"):
                op25_overrides[sname]["whitelist"] = whitelist_path

    # Detect traffic follower dongle from allocator's traffic pool.
    traffic_serial = _detect_traffic_dongle(dongle_assignments)
    traffic_system = ""
    if traffic_serial:
        traffic_system = systems[0]["name"] if systems else ""
        print(f"OP25 runtime: traffic follower dongle={traffic_serial} -> {traffic_system}")
    else:
        print("OP25 runtime: no traffic follower dongle available")

    requested_serials = list(dongle_map.values())
    if traffic_serial:
        requested_serials.append(traffic_serial)
    dongle_args_map = _build_dongle_arg_map(requested_serials)
    if dongle_args_map:
        for serial in requested_serials:
            serial = str(serial or "").strip()
            if not serial:
                continue
            resolved = dongle_args_map.get(serial, f"rtl={serial}")
            print(f"OP25 runtime: resolved tuner {serial} -> {resolved}")

    # Generate multi_rx.py JSON config.
    config = generate_multi_rx_config(
        systems,
        dongle_map,
        dongle_args_map=dongle_args_map,
        traffic_dongle_serial=traffic_serial,
        traffic_system_name=traffic_system,
        op25_overrides=op25_overrides,
        tgid_tags_path=tags_path,
        http_port=OP25_STATUS_PORT,
        udp_audio_base_port=_UDP_AUDIO_BASE_PORT,
        sample_rate=OP25_DEFAULT_SAMPLE_RATE,
        offset=OP25_DEFAULT_OFFSET,
    )

    config_path = os.path.join(runtime_dir, "multi_rx.json")
    _atomic_write(config_path, json.dumps(config, indent=2) + "\n")
    print(f"OP25 runtime: wrote {config_path}")

    # Write trunk.tsv from the same systems/overrides used for multi_rx.json.
    trunk_path = os.path.join(runtime_dir, "trunk.tsv")
    trunk_content = generate_trunk_tsv(
        systems,
        dongle_assignments=dongle_assignments,
        op25_overrides=op25_overrides,
        tgid_tags_path=tags_path,
    )
    _atomic_write(trunk_path, trunk_content)
    print(f"OP25 runtime: wrote {trunk_path}")

    # Print device/channel summary.
    for dev in config.get("devices", []):
        print(
            f"  device {dev['name']}: args={dev['args']}  "
            f"center={dev['frequency']/1e6:.5f} MHz  rate={dev['rate']/1e6:.1f}M"
        )
    for ch in config.get("channels", []):
        print(
            f"  channel {ch['name']}: device={ch['device']}  "
            f"system={ch['trunking_sysname']}  dest={ch['destination']}"
        )

    # Generate start.sh.
    start_script = _generate_multi_rx_start_script(config_path)
    start_path = os.path.join(runtime_dir, "start.sh")
    _atomic_write(start_path, start_script)
    os.chmod(
        start_path,
        stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH,
    )
    print(f"OP25 runtime: wrote {start_path}")

    # Write instances manifest for audio bridge and adapter compatibility.
    _multi_rx_udp_ports(config)
    instances_manifest = []
    for ch_idx, ch in enumerate(config.get("channels", [])):
        dest = ch.get("destination", "")
        udp_port = 0
        if dest.startswith("udp://"):
            try:
                udp_port = int(dest.rsplit(":", 1)[1])
            except (ValueError, IndexError):
                pass
        instances_manifest.append({
            "index": ch_idx,
            "channel_name": ch.get("name", ""),
            "system_name": ch.get("trunking_sysname", ""),
            "device_name": ch.get("device", ""),
            "udp_audio_port": udp_port,
            "http_status_port": OP25_STATUS_PORT,
        })

    manifest_path = os.path.join(runtime_dir, "instances.json")
    _atomic_write(manifest_path, json.dumps(instances_manifest, indent=2) + "\n")
    print(f"OP25 runtime: wrote {manifest_path} ({len(instances_manifest)} channels)")

    print(f"OP25 runtime: ready ({len(config['devices'])} devices, {len(config['channels'])} channels)")
    return 0


def _atomic_write(path: str, content: str) -> None:
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(content)
    os.replace(tmp, path)


if __name__ == "__main__":
    sys.exit(main())
